name: solid_crdt_sync_annotations
description: CRDT merge strategy annotations for solid_crdt_sync code generation
version: 0.1.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  rdf_mapper_annotations: ^0.10.1

dev_dependencies:
  test: ^1.21.0

topics:
  - rdf
  - crdt
  - solid
  - annotations
  - codegen