name: pacors_workspace
description: Workspace for the pacors monorepo
version: 0.9.15-dev
homepage: https://kkalass.github.io/pacors/
repository: https://github.com/kkalass/pacors
issue_tracker: https://github.com/kkalass/pacors/issues
documentation: https://kkalass.github.io/pacors/
publish_to: none

environment:
  sdk: ^3.6.0

dev_dependencies:
  melos: ^6.1.0
