name: solid_crdt_sync_workspace
description: Workspace for the solid_crdt_sync monorepo
version: 0.9.15-dev
homepage: https://kkalass.github.io/solid_crdt_sync/
repository: https://github.com/kkalass/solid_crdt_sync
issue_tracker: https://github.com/kkalass/solid_crdt_sync/issues
documentation: https://kkalass.github.io/solid_crdt_sync/
publish_to: none

environment:
  sdk: ^3.6.0

dev_dependencies:
  melos: ^7.1.0
