name: pacors_solid_auth
description: Solid authentication implementation for pacors using solid-auth
version: 0.9.15-dev
homepage: https://kkalass.github.io/pacors/
repository: https://github.com/kkalass/pacors
issue_tracker: https://github.com/kkalass/pacors/issues
publish_to: none

topics:
  - solid
  - authentication
  - oidc

environment:
  sdk: ^3.6.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  pacors_core:
    path: ../pacors_core
  pacors_solid:
    path: ../pacors_solid
  # Solid authentication
  # TODO: Use published version when available
  solid_auth:
    git:
      url: https://github.com/kkalass/solid_auth.git
      ref: feat/migrate-to-bdaya-oidc-security-fix
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ">=5.1.1 <7.0.0"

flutter:
  generate: true

# TODO: Remove when solid_auth and a fixed oidc_core are published
dependency_overrides:
  oidc_core:
    git:
      url: https://github.com/kkalass/oidc.git
      ref: fix/oidc-hook-execute-stack-overflow
      path: packages/oidc_core
