name: pacors_solid
description: Solid Pod backend implementation for PACORS CRDT synchronization
version: 0.9.15-dev
homepage: https://kkalass.github.io/pacors/
repository: https://github.com/kkalass/pacors
issue_tracker: https://github.com/kkalass/pacors/issues
documentation: https://kkalass.github.io/pacors/
publish_to: none

topics:
  - rdf
  - linked-data
  - semantic-web
  - crdt
  - solid

environment:
  sdk: ^3.6.0

dependencies:
  logging: ^1.2.0

  # Core PACORS dependencies
  pacors_core:
    path: ../pacors_core

  # HTTP client for Solid Pod communication
  http: ^1.1.0

dev_dependencies:
  test: ^1.24.0
  lints: ">=5.1.1 <7.0.0"