name: solid_crdt_sync_auth
description: Solid authentication implementation for solid_crdt_sync using solid-auth
version: 0.9.15-dev
homepage: https://kkalass.github.io/solid_crdt_sync/
repository: https://github.com/kkalass/solid_crdt_sync
issue_tracker: https://github.com/kkalass/solid_crdt_sync/issues
publish_to: none

topics:
  - solid
  - authentication
  - oidc

environment:
  sdk: ^3.6.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  solid_crdt_sync_core:
    path: ../solid_crdt_sync_core
  # TODO: Add solid-auth dependency once available
  # solid_auth: ^x.x.x

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ">=5.1.1 <7.0.0"