/// Personal Notes App - Simple local-first application using solid_crdt_sync.
///
/// Demonstrates:
/// - Local-first operation (works offline)
/// - Optional Solid Pod connection
/// - CRDT conflict resolution
/// - Simple, clean UI
library;

import 'package:flutter/material.dart';
import 'package:personal_notes_app/init_rdf_mapper.g.dart';
import 'package:rdf_core/rdf_core.dart';
import 'package:rdf_mapper/rdf_mapper.dart';
import 'package:solid_crdt_sync_core/solid_crdt_sync_core.dart';
import 'package:solid_crdt_sync_drift/solid_crdt_sync_drift.dart';

import 'screens/notes_list_screen.dart';
import 'services/notes_service.dart';

// TODO: This will be generated by build_runner
// import 'models/note.mapper.g.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize with generated mappers
  final rdfMapper = await initRdfMapper();

  // Set up the CRDT sync system - works locally by default
  final syncSystem = await SolidCrdtSync.setup(
    storage: DriftStorage(),
    mapper: rdfMapper,
    // authProvider is optional - app works locally first
  );

  // Initialize notes service
  final notesService = NotesService(syncSystem);

  runApp(PersonalNotesApp(
    syncSystem: syncSystem,
    notesService: notesService,
  ));
}

class PersonalNotesApp extends StatelessWidget {
  final SolidCrdtSync syncSystem;
  final NotesService notesService;

  const PersonalNotesApp({
    super.key,
    required this.syncSystem,
    required this.notesService,
  });

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Personal Notes',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
        useMaterial3: true,
      ),
      home: NotesListScreen(
        syncSystem: syncSystem,
        notesService: notesService,
      ),
    );
  }
}
