name: Dart CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.4'
          
      # Install workspace dependencies
      - name: Install workspace dependencies  
        run: dart pub get
        
      # Bootstrap melos workspace
      - name: Bootstrap melos workspace
        run: dart pub run melos bootstrap
        
      # Run analysis across all packages
      - name: Analyze all packages
        run: dart pub run melos analyze
        
      # Run tests across all packages
      - name: Run tests across all packages  
        run: dart pub run melos test
        
      # Note: Coverage aggregation across packages is complex
      # For now, we run tests without coverage in CI
      # Individual package coverage can be run locally
